name: Deploy to Infinity Free

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Infinity Free
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_DIRECTORY: /htdocs
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -c "
            set ftp:list-options -a;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
            cd $FTP_DIRECTORY;
            mirror -R ./ ./
          "
